# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: VaultReadKV@4
  inputs:
    strUrl: 'https://vault-cluster.vault.cbc46428-c9b4-41b4-9d99-b3a66e51d633.aws.hashicorp.cloud:8200'
    ignoreCertificateChecks: false
    useProxy: 'none'
    strAuthType: 'clientToken'
    strToken: 'test'
    strKVEnginePath: 'secret'
    kvVersion: 'v2'
    strSecretPath: '/cicd/dev'
    strPrefixType: 'custom'
    strVariablePrefix: 'dev-14'
    replaceCR: false
